<?php
include_once("db_connect.php");
include_once("manage_sessions.php");
include_once("functions.php");
include_once("manageSettings.php");
include_once("manageAccount.php");
include_once("manageLogin.php");
include_once("managePosts.php");
include_once("manageLikes.php");
include_once("manageComments.php");
include_once("manageNotifications.php");
include_once("manageAlbum.php");
include_once("manageFriends.php");
include_once("manageMessages.php");
include_once("managePages.php");
include_once("manageEvents.php");
include_once("manageAttending.php");
include_once("manageTokkens.php");